### ISSUE TITLE
SSI Kapitel 1.4/1.5 -> Zusammenfasse

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#13]

**Comment by aeklap** [comment]
done und gekürzt und umgestellt. Beim Abschnitt "Web of Trust" in Kapitel 1.5 müssen wir noch schauen ob das so als Abschnitt bleibt oder anders eingefügt wird.

**Comment by Echsecutor** [comment]
Danke @aeklap ! Ich lese die Kapitel auf jeden Fall auch noch
