### ISSUE TITLE
LEI Abschnitt

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#16]
Ich finde den Abschneitt zur LEI interessant, aber eigentlich tut es für uns nichts zur Sache wie die LEI aufgebaut ist (welche Stellen welche Bedeutung haben), oder? Ich würde Vorschlagen diesen Abschnitt in den Anhang zu verschieben, was meint ihr?

**Comment by aeklap** [comment]
Wir können 1.3.2 verschieben, das Wesentliche steht ja auch in 1.3.3 und wie du bereits sagst, ist der Fokus auf die LEI etwas verschwunden.

**Comment by winnitou** [comment]
Müssen wir den LEI Abschnitt überhaupt noch im Dokument haben? Oder sollen wir den komplett rausnehmen?

**Comment by Echsecutor** [comment]
Teil in Anhang

**Comment by aeklap** [comment]
Frank stellt erneut in Frage, ob wir LEI als Thema einbringen oder besser nur auf GS1 System fokussieren

**Comment by aeklap** [comment]
Laut Management soll LEI als Kapitel rausfallen wenn wir nicht alle existierenden Idente vorstellen
