### ISSUE TITLE
Glossar anlegen

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#17]
gut Idee von Ralph

**Comment by winnitou** [comment]
Aufgrund der Zeit für später eingeplant

**Comment by Echsecutor** [comment]
Ascii Doc Syntax für das Glossar: https://asciidoctor.org/docs/user-manual/#user-glossary

Sinnvoll wäre wahrscheinlich neben evtl 1 Satz zur erläuterung der Begriffe vor allem ein Verweis auf den relevanten Abschnitt, in dem der Begrif erklärt wird.

**Comment by Echsecutor** [comment]
Ich habe hier https://github.com/gs1-germany-innolab/CertifiedByGS1-Konzepte/commit/84f0601bd35705d6eab99b79d1bf20998e924bea den ersten Beispiel Begriff hinzugefügt

**Comment by Echsecutor** [comment]
@CastellanosGS1 gibt es Probleme? Ich sehe noch nichts vom Glossar  im aktuellen Dokument

**Comment by CastellanosGS1** [comment]
@Echsecutor bin noch gar nicht dazu gekommen, habe mir ein Blocker für Mittworch-Donnerstag dafür gemacht.

**Comment by Echsecutor** [comment]
wir haben besprochen, dass LEI nicht mehr erwähnt wird, d.h. bitte aus dem Glossar raus lassen.
