### ISSUE TITLE
Tabelle 1 Eigenschaften von Identifikatoren fehlt

### ISSUE THREAD

**Issue by aeklap** [gs1-germany-innolab/CertifiedByGS1-Konzepte#19]
Im Abschnitt der DIDs (Kap. 1.5) fehlt unter dem Vergleich der Identifikatoren die Tabelle. Haben wir die irgendwo und benötigen wir sie tatsächlich?

**Comment by winnitou** [comment]
Die Tabelle hattest du einmal in einem Dokument erstellt gehabt. 
![image](https://user-images.githubusercontent.com/4614306/95584338-d7848080-0a3d-11eb-9bef-39aa9ca3f50c.png)

Können wir aber auch löschen

**Comment by aeklap** [comment]
Wir können sie auch einfügen, sie ist nur momentan nicht sichbar

**Comment by Echsecutor** [comment]
bin dran

**Comment by Echsecutor** [comment]
siehe #33
