### ISSUE TITLE
URN oder URI?

### ISSUE THREAD

**Issue by aeklap** [gs1-germany-innolab/CertifiedByGS1-Konzepte#20]
Im Abschnitt "Vergleich mit anderen Identifiern" im Kapitel 1.5 schreiben wir:
"Der Bedarf an persistenten – dauerhaft einer Entität zugewiesenen und unveränderlichen – Kennzeichnern, welche gleichzeitig global auflösbar sind, ist ebenso wenig neu. Diese Art der Kennzeichner wurden als URNs (Uniform Resource Names)
standardisiert ([rfc-2141], RFC 8141)."

Ralph merkt hier an: URNs sind *nicht* ohne weiteres auflösbar, nur  URLs und z.T. Web URIs 
URIs = URLs + Web URIs + URNs

Was stimmt nun?

**Comment by Echsecutor** [comment]
Ich glaube, die Frage ist hier, was wir mit "auflösbar" meinen. ;)
Als Brause eignen die sich alle nicht, aber an eine URL kann ich ohne weiteres ein HTTP GET schicken, an eine URN erst mal nicht.

Ich verstricke mich auch immer leicht in den Bezeichnungen ( https://en.wikipedia.org/wiki/Urn ) 

Eine URN ist prinzipiell der persistente Bezeichner für eine Sache (z.B. ein digital object identifier DOI) währende die URL auf einen konkreten Ort verweist, an dem ich die Sache finden kann. URNs und URLs sind beides URIs.

**Comment by Echsecutor** [comment]
Ich kümmere mich drum, wenn ich den entsprechenden Abschnitt lese, ok?

**Comment by Echsecutor** [comment]
wird in #33 mit erledigt
