### ISSUE TITLE
ID/Ident/Identifikator/Identifikationsnummer/...

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#23]
Das ist ein Begriff den wir häufig benutzen. In der Regel verwenden wir "Ident" was glaube ich üblicher GS1-Sprech ist, wenn auch kein deutsches Duden-Wort.

Ich habe nun schon hier und da Synonyme auf "Ident" korrigiert -> lassen wir so oder nehmen wir was anderes?

"Identifikationsnummer" wäre das Duden-Wort, was nicht immer ganz passt, da es sich manchmal auch um z.B. eine URN handelt.

**Comment by winnitou** [comment]
GS1 Identifikationsnummer oder GS1 Identifikationsschlüssel ist in Ordnung. Das benutzen wir auch bei uns in den Dokumenten

**Comment by winnitou** [comment]
Ident liest sich jedoch teilweise besser und kann von mir aus auch genutzt werden.

**Comment by Echsecutor** [comment]
Ok, ich würde dann bevorzug Identifikationsnummer/Identifikationsschlüssel verwenden

**Comment by Echsecutor** [comment]
ToDo: Das ganze Dokument zu durchsuchen und "Ident" duchr "Identifikationsnummer" erstzen (+Grammatik in der Umgebung).

**Comment by Echsecutor** [comment]
Ident/Identifiksationsnummer/Identifikationsschlüssel ok. Rest ersetzen falls noch vorhanden
