### ISSUE TITLE
Zusätzliche Intermediates möglich

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#38]
GS1 Keys von Dritten vergeben werden. Es gibt mehrere Beispiele, in denen GS1 GO/GS1 MOs entsprechende Verträge geschlossen haben – GS1 Germany bspw. mit GLOBALGAP. 

-> Sihee Ralfs Mail

Erwähnen/Bild mit einbeziehen

**Comment by winnitou** [comment]
Ich bin mir nicht sicher wie wir uns derzeitig wirklich zu GLOBALGAP positionieren. Ob wir die Lösung gut finden oder nicht. Evtl. müsste so etwas auch im Management entscheiden werden.

**Comment by Echsecutor** [comment]
kein GAP
