### ISSUE TITLE
Kein schutz vor kopieren der Signatur/des auto-id labels

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany-innolab/CertifiedByGS1-Konzepte#41]

**Comment by Echsecutor** [comment]
Die stelle ist:

> Auch Eigenschaften des mit dem Ident gekennzeichneten Assets können über die GS1
Standards, beispielsweise in einen 2D Code wie der GS1 DataMatrix, kodiert und deren
Vertrauenswürdigkeit offline verifiziert werden.

Hinzufügen: Kein Kopierschutz, insbesondere nicht für das auto-ID Label

**Comment by winnitou** [comment]
Siehe #63
