### ISSUE TITLE
Vergleichstabelle zwischen X.509 und SSI erstellen

### ISSUE THREAD

**Issue by winnitou** [gs1-germany-innolab/CertifiedByGS1-Konzepte#64]
Aus Kapitel "2.4. Realisierung uber X.509 im Vergleich zu Verifiable Credentials"

**Comment by Echsecutor** [comment]
besser erklären und evtl Bild oder Tabelle einfügen

**Comment by Echsecutor** [comment]
X509 <-> VC

**Comment by winnitou** [comment]
Falls zu finden ein Bild oder Schema hinzufügen.

•	Schema von VC ist sehr flexibel
•	Das Datenformat ist frei zugänglich und frei wählbar
•	bei X509 hängt man an der LDAP Syntax
