### ISSUE TITLE
Bild 12

### ISSUE THREAD

**Issue by winnitou** [gs1-germany-innolab/CertifiedByGS1-Konzepte#66]
„Was haltet ihr davon, statt der EPC URI Notation auf GS1 DL URIs zu gehen - die hätten gleich von anfang an den Vorteil, auflösbar zu sein und würden unmittelbar Web Requests ermöglichen - das wäre aus meiner SIcht in diesem Kontext viel eleganter“

**Comment by winnitou** [comment]
Würde ich nicht machen. DIDs sind doch auch URN ähnlich

**Comment by aeklap** [comment]
Ich würde auch die DL Web URIs weglassen. Wir müssten zudem noch ein ganzes Kapitel zum Digital Link einbringen

**Comment by winnitou** [comment]
Da Digital Links noch beschrieben werden müssten und hier keinen erheblichen Mehrwert bieten, wird die URN Schreibweise belassen.
