### ISSUE TITLE
3.3.1 EKU Nennung

### ISSUE THREAD

**Issue by CastellanosGS1** [gs1-germany-innolab/CertifiedByGS1-Konzepte#74]
Hast du nach Erlaubnis gefragt? sollten die auch den Teil reviewen?

**Comment by Echsecutor** [comment]
Ich habe schon lange mit denen abgesprochen, dass die gerne genannt werden möchten.

Wir sollten denen das Paper auch zum review schicken, guter Punkt! Ich kümmere mich drum

**Comment by Echsecutor** [comment]
Ich habe Kristian eine Mail geschrieben und freundlich um Review gebeten
