### ISSUE TITLE
3.3.3 Zweite Paragraph Umformulierung

### ISSUE THREAD

**Issue by CastellanosGS1** [gs1-germany-innolab/CertifiedByGS1-Konzepte#76]
RT: Das verstehe ich nicht. Wieso "ebenso vorhersehbar"?

**Comment by Echsecutor** [comment]
Ich kann die stelle im aktuellen Dokument nicht mehr finden.

Hat sich erledigt?

**Comment by CastellanosGS1** [comment]
Hi, ja, den Text würde angepasst ;)
